-- GOALS
-- 1) Sanity
-- 2) Sanity
-- 3) Common Sense
-- 4) Keep backlog of stats for the past 10 days, weeks, and months
-- 5) Sanity

CREATE TABLE `ats_etc` (
  `admin_password` varchar(32) default '',
  `last_new_day` tinyint(4) default '0',
  `last_new_week` tinyint(4) default '0',
  `last_new_month` tinyint(4) default '0'
);

CREATE TABLE `ats_ip_log` (
  `ip_address` varchar(32) default '',
  `id` bigint(20) unsigned default '0',
  `unq_pv` tinyint(1) default '',
  `unq_in` tinyint(1) default '',
  `unq_out` tinyint(1) default '',
  `review` tinyint(1) default ''
);

CREATE TABLE `ats_members` (
  `id` bigint(20) unsigned default '0',
  `password` varchar(32) default '',
  `url` varchar(70) default '',
  `title` varchar(32) default '',
  `description` varchar(255) default '',
  `category` varchar(255) default '',
  `banner_url` varchar(90) default '',
  `email` varchar(70) default '',
  `join_time` datetime default '0000-00-00 00:00:00',
  `active` tinyint(1) default '1',
  PRIMARY KEY  (`id`)
);

CREATE TABLE `ats_reviews` (
  `id` bigint(20) unsigned default '0',
  `review_id` bigint(20) unsigned default '0',
  `review_date` datetime default '0000-00-00 00:00:00',
  `review` text,
  PRIMARY KEY  (`review_id`)
);

CREATE TABLE `ats_sessions` (
  `type` varchar(7) default '',
  `session_id` varchar(24) default '',
  `created` int(10) default '',
  `data` varchar(255) default ''
);

CRATE TABLE `ats_stats_general` (
  `id` bigint(20) unsigned default '0',
  `old_rank` bigint(20) unsigned default '0',
  `days_inactive` int(10) unsigned default '0',
  `total_rating` bigint(20) unsigned default '0',
  `num_ratings` bigint(20) unsigned default '0'
);

CREATE TABLE `ats_stats_daily` (
  `id` bigint(20) unsigned default '0',
  `unq_pv_0` bigint(20) unsigned default '0',
  `unq_pv_1` bigint(20) unsigned default '0',
  `unq_pv_2` bigint(20) unsigned default '0',
  `unq_pv_3` bigint(20) unsigned default '0',
  `unq_pv_4` bigint(20) unsigned default '0',
  `unq_pv_5` bigint(20) unsigned default '0',
  `unq_pv_6` bigint(20) unsigned default '0',
  `unq_pv_7` bigint(20) unsigned default '0',
  `unq_pv_8` bigint(20) unsigned default '0',
  `unq_pv_9` bigint(20) unsigned default '0',
  `unq_pv_max` bigint(20) unsigned default '0',
  `tot_pv_0` bigint(20) unsigned default '0',
  `tot_pv_1` bigint(20) unsigned default '0',
  `tot_pv_2` bigint(20) unsigned default '0',
  `tot_pv_3` bigint(20) unsigned default '0',
  `tot_pv_4` bigint(20) unsigned default '0',
  `tot_pv_5` bigint(20) unsigned default '0',
  `tot_pv_6` bigint(20) unsigned default '0',
  `tot_pv_7` bigint(20) unsigned default '0',
  `tot_pv_8` bigint(20) unsigned default '0',
  `tot_pv_9` bigint(20) unsigned default '0',
  `tot_pv_max` bigint(20) unsigned default '0',
  `unq_in_0` bigint(20) unsigned default '0',
  `unq_in_1` bigint(20) unsigned default '0',
  `unq_in_2` bigint(20) unsigned default '0',
  `unq_in_3` bigint(20) unsigned default '0',
  `unq_in_4` bigint(20) unsigned default '0',
  `unq_in_5` bigint(20) unsigned default '0',
  `unq_in_6` bigint(20) unsigned default '0',
  `unq_in_7` bigint(20) unsigned default '0',
  `unq_in_8` bigint(20) unsigned default '0',
  `unq_in_9` bigint(20) unsigned default '0',
  `unq_in_max` bigint(20) unsigned default '0',
  `tot_in_0` bigint(20) unsigned default '0',
  `tot_in_1` bigint(20) unsigned default '0',
  `tot_in_2` bigint(20) unsigned default '0',
  `tot_in_3` bigint(20) unsigned default '0',
  `tot_in_4` bigint(20) unsigned default '0',
  `tot_in_5` bigint(20) unsigned default '0',
  `tot_in_6` bigint(20) unsigned default '0',
  `tot_in_7` bigint(20) unsigned default '0',
  `tot_in_8` bigint(20) unsigned default '0',
  `tot_in_9` bigint(20) unsigned default '0',
  `tot_in_max` bigint(20) unsigned default '0',
  `unq_out_0` bigint(20) unsigned default '0',
  `unq_out_1` bigint(20) unsigned default '0',
  `unq_out_2` bigint(20) unsigned default '0',
  `unq_out_3` bigint(20) unsigned default '0',
  `unq_out_4` bigint(20) unsigned default '0',
  `unq_out_5` bigint(20) unsigned default '0',
  `unq_out_6` bigint(20) unsigned default '0',
  `unq_out_7` bigint(20) unsigned default '0',
  `unq_out_8` bigint(20) unsigned default '0',
  `unq_out_9` bigint(20) unsigned default '0',
  `unq_out_max` bigint(20) unsigned default '0',
  `tot_out_0` bigint(20) unsigned default '0',
  `tot_out_1` bigint(20) unsigned default '0',
  `tot_out_2` bigint(20) unsigned default '0',
  `tot_out_3` bigint(20) unsigned default '0',
  `tot_out_4` bigint(20) unsigned default '0',
  `tot_out_5` bigint(20) unsigned default '0',
  `tot_out_6` bigint(20) unsigned default '0',
  `tot_out_7` bigint(20) unsigned default '0',
  `tot_out_8` bigint(20) unsigned default '0',
  `tot_out_9` bigint(20) unsigned default '0',
  `tot_out_max` bigint(20) unsigned default '0',
  PRIMARY KEY  (`id`)
);

CREATE TABLE `ats_stats_weekly` (
  `id` bigint(20) unsigned default '0',
  `unq_pv_0` bigint(20) unsigned default '0',
  `unq_pv_1` bigint(20) unsigned default '0',
  `unq_pv_2` bigint(20) unsigned default '0',
  `unq_pv_3` bigint(20) unsigned default '0',
  `unq_pv_4` bigint(20) unsigned default '0',
  `unq_pv_5` bigint(20) unsigned default '0',
  `unq_pv_6` bigint(20) unsigned default '0',
  `unq_pv_7` bigint(20) unsigned default '0',
  `unq_pv_8` bigint(20) unsigned default '0',
  `unq_pv_9` bigint(20) unsigned default '0',
  `unq_pv_max` bigint(20) unsigned default '0',
  `tot_pv_0` bigint(20) unsigned default '0',
  `tot_pv_1` bigint(20) unsigned default '0',
  `tot_pv_2` bigint(20) unsigned default '0',
  `tot_pv_3` bigint(20) unsigned default '0',
  `tot_pv_4` bigint(20) unsigned default '0',
  `tot_pv_5` bigint(20) unsigned default '0',
  `tot_pv_6` bigint(20) unsigned default '0',
  `tot_pv_7` bigint(20) unsigned default '0',
  `tot_pv_8` bigint(20) unsigned default '0',
  `tot_pv_9` bigint(20) unsigned default '0',
  `tot_pv_max` bigint(20) unsigned default '0',
  `unq_in_0` bigint(20) unsigned default '0',
  `unq_in_1` bigint(20) unsigned default '0',
  `unq_in_2` bigint(20) unsigned default '0',
  `unq_in_3` bigint(20) unsigned default '0',
  `unq_in_4` bigint(20) unsigned default '0',
  `unq_in_5` bigint(20) unsigned default '0',
  `unq_in_6` bigint(20) unsigned default '0',
  `unq_in_7` bigint(20) unsigned default '0',
  `unq_in_8` bigint(20) unsigned default '0',
  `unq_in_9` bigint(20) unsigned default '0',
  `unq_in_max` bigint(20) unsigned default '0',
  `tot_in_0` bigint(20) unsigned default '0',
  `tot_in_1` bigint(20) unsigned default '0',
  `tot_in_2` bigint(20) unsigned default '0',
  `tot_in_3` bigint(20) unsigned default '0',
  `tot_in_4` bigint(20) unsigned default '0',
  `tot_in_5` bigint(20) unsigned default '0',
  `tot_in_6` bigint(20) unsigned default '0',
  `tot_in_7` bigint(20) unsigned default '0',
  `tot_in_8` bigint(20) unsigned default '0',
  `tot_in_9` bigint(20) unsigned default '0',
  `tot_in_max` bigint(20) unsigned default '0',
  `unq_out_0` bigint(20) unsigned default '0',
  `unq_out_1` bigint(20) unsigned default '0',
  `unq_out_2` bigint(20) unsigned default '0',
  `unq_out_3` bigint(20) unsigned default '0',
  `unq_out_4` bigint(20) unsigned default '0',
  `unq_out_5` bigint(20) unsigned default '0',
  `unq_out_6` bigint(20) unsigned default '0',
  `unq_out_7` bigint(20) unsigned default '0',
  `unq_out_8` bigint(20) unsigned default '0',
  `unq_out_9` bigint(20) unsigned default '0',
  `unq_out_max` bigint(20) unsigned default '0',
  `tot_out_0` bigint(20) unsigned default '0',
  `tot_out_1` bigint(20) unsigned default '0',
  `tot_out_2` bigint(20) unsigned default '0',
  `tot_out_3` bigint(20) unsigned default '0',
  `tot_out_4` bigint(20) unsigned default '0',
  `tot_out_5` bigint(20) unsigned default '0',
  `tot_out_6` bigint(20) unsigned default '0',
  `tot_out_7` bigint(20) unsigned default '0',
  `tot_out_8` bigint(20) unsigned default '0',
  `tot_out_9` bigint(20) unsigned default '0',
  `tot_out_max` bigint(20) unsigned default '0',
  PRIMARY KEY  (`id`)
);

CREATE TABLE `ats_stats_monthly` (
  `id` bigint(20) unsigned default '0',
  `unq_pv_0` bigint(20) unsigned default '0',
  `unq_pv_1` bigint(20) unsigned default '0',
  `unq_pv_2` bigint(20) unsigned default '0',
  `unq_pv_3` bigint(20) unsigned default '0',
  `unq_pv_4` bigint(20) unsigned default '0',
  `unq_pv_5` bigint(20) unsigned default '0',
  `unq_pv_6` bigint(20) unsigned default '0',
  `unq_pv_7` bigint(20) unsigned default '0',
  `unq_pv_8` bigint(20) unsigned default '0',
  `unq_pv_9` bigint(20) unsigned default '0',
  `unq_pv_max` bigint(20) unsigned default '0',
  `tot_pv_0` bigint(20) unsigned default '0',
  `tot_pv_1` bigint(20) unsigned default '0',
  `tot_pv_2` bigint(20) unsigned default '0',
  `tot_pv_3` bigint(20) unsigned default '0',
  `tot_pv_4` bigint(20) unsigned default '0',
  `tot_pv_5` bigint(20) unsigned default '0',
  `tot_pv_6` bigint(20) unsigned default '0',
  `tot_pv_7` bigint(20) unsigned default '0',
  `tot_pv_8` bigint(20) unsigned default '0',
  `tot_pv_9` bigint(20) unsigned default '0',
  `tot_pv_max` bigint(20) unsigned default '0',
  `unq_in_0` bigint(20) unsigned default '0',
  `unq_in_1` bigint(20) unsigned default '0',
  `unq_in_2` bigint(20) unsigned default '0',
  `unq_in_3` bigint(20) unsigned default '0',
  `unq_in_4` bigint(20) unsigned default '0',
  `unq_in_5` bigint(20) unsigned default '0',
  `unq_in_6` bigint(20) unsigned default '0',
  `unq_in_7` bigint(20) unsigned default '0',
  `unq_in_8` bigint(20) unsigned default '0',
  `unq_in_9` bigint(20) unsigned default '0',
  `unq_in_max` bigint(20) unsigned default '0',
  `tot_in_0` bigint(20) unsigned default '0',
  `tot_in_1` bigint(20) unsigned default '0',
  `tot_in_2` bigint(20) unsigned default '0',
  `tot_in_3` bigint(20) unsigned default '0',
  `tot_in_4` bigint(20) unsigned default '0',
  `tot_in_5` bigint(20) unsigned default '0',
  `tot_in_6` bigint(20) unsigned default '0',
  `tot_in_7` bigint(20) unsigned default '0',
  `tot_in_8` bigint(20) unsigned default '0',
  `tot_in_9` bigint(20) unsigned default '0',
  `tot_in_max` bigint(20) unsigned default '0',
  `unq_out_0` bigint(20) unsigned default '0',
  `unq_out_1` bigint(20) unsigned default '0',
  `unq_out_2` bigint(20) unsigned default '0',
  `unq_out_3` bigint(20) unsigned default '0',
  `unq_out_4` bigint(20) unsigned default '0',
  `unq_out_5` bigint(20) unsigned default '0',
  `unq_out_6` bigint(20) unsigned default '0',
  `unq_out_7` bigint(20) unsigned default '0',
  `unq_out_8` bigint(20) unsigned default '0',
  `unq_out_9` bigint(20) unsigned default '0',
  `unq_out_max` bigint(20) unsigned default '0',
  `tot_out_0` bigint(20) unsigned default '0',
  `tot_out_1` bigint(20) unsigned default '0',
  `tot_out_2` bigint(20) unsigned default '0',
  `tot_out_3` bigint(20) unsigned default '0',
  `tot_out_4` bigint(20) unsigned default '0',
  `tot_out_5` bigint(20) unsigned default '0',
  `tot_out_6` bigint(20) unsigned default '0',
  `tot_out_7` bigint(20) unsigned default '0',
  `tot_out_8` bigint(20) unsigned default '0',
  `tot_out_9` bigint(20) unsigned default '0',
  `tot_out_max` bigint(20) unsigned default '0',
  PRIMARY KEY  (`id`)
);
